# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

botCfun <- function(base_order_volume, first_safety_order_volume, n_safety_orders, take_profit, pricescale, volumescale, pricemult, stoploss, trailing_take_profit, trailing_rate, trading_fee, show_trades, plot, start_asap, compound, use_emergency_stop, price, date, deal_start, emergency_stop) {
    .Call(`_martingalebot_botCfun`, base_order_volume, first_safety_order_volume, n_safety_orders, take_profit, pricescale, volumescale, pricemult, stoploss, trailing_take_profit, trailing_rate, trading_fee, show_trades, plot, start_asap, compound, use_emergency_stop, price, date, deal_start, emergency_stop)
}

